# Generated by Django 5.0.6 on 2024-07-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_image_alter_blog_user_alter_comment_blog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.CharField(max_length=500),
        ),
    ]
