# Generated by Django 5.0.6 on 2024-07-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_alter_blog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='/blog_picture/noticia.jpg', null=True, upload_to='blog_picture/'),
        ),
    ]
