# Generated by Django 5.1 on 2024-08-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0019_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='blog_picture/noticia.jpg', null=True, upload_to='blog_picture/'),
        ),
    ]
