# Generated by Django 5.1.1 on 2024-09-10 23:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0021_historicalblog_historicalcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='blog_picture/noticia.jpg', null=True, upload_to='blog_picture/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'tiff', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='historicalblog',
            name='image',
            field=models.TextField(blank=True, default='blog_picture/noticia.jpg', max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'tiff', 'webp'])]),
        ),
    ]
