# Generated by Django 5.0.7 on 2024-07-22 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0004_alter_suggestion_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
