# Generated by Django 5.0.7 on 2024-07-22 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0005_suggestion_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
