# Generated by Django 5.0.6 on 2024-07-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_rename_name_application_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='applicationclassification',
            name='description',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
