# Generated by Django 5.1.1 on 2024-09-10 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_historicalapplication_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalapplicationclassification',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical application classification', 'verbose_name_plural': 'historical application classifications'},
        ),
    ]
