# Generated by Django 5.1.1 on 2024-09-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_alter_historicalapplicationclassification_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='applicationclassification',
            new_name='applicationClassification',
        ),
        migrations.RenameField(
            model_name='historicalapplication',
            old_name='applicationclassification',
            new_name='applicationClassification',
        ),
        migrations.AlterField(
            model_name='application',
            name='data',
            field=models.FileField(blank=True, null=True, upload_to='tools/'),
        ),
    ]
