# Generated by Django 5.1.1 on 2024-09-10 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_rename_applicationclassification_application_applicationclassification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='applicationClassification',
            new_name='applicationclassification',
        ),
        migrations.RenameField(
            model_name='historicalapplication',
            old_name='applicationClassification',
            new_name='applicationclassification',
        ),
    ]
