# Generated by Django 5.1.1 on 2024-09-10 23:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_rename_applicationclassification_application_applicationclassification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='data',
            field=models.FileField(blank=True, null=True, upload_to='tools/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'tar', 'gz', 'bz2', '7z', 'rar'])]),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='data',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'tar', 'gz', 'bz2', '7z', 'rar'])]),
        ),
    ]
