# Generated by Django 5.0.6 on 2024-07-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0005_rename_name_multimedia_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimedia',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='multimediaclassification',
            name='description',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
