# Generated by Django 5.1.1 on 2024-09-10 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0007_historicalmultimedia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalmultimediaclassification',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical multimedia classification', 'verbose_name_plural': 'historical multimedia classifications'},
        ),
        migrations.RenameField(
            model_name='historicalmultimedia',
            old_name='multimediaclassification',
            new_name='multimediaClassification',
        ),
        migrations.RenameField(
            model_name='multimedia',
            old_name='multimediaclassification',
            new_name='multimediaClassification',
        ),
    ]
