# Generated by Django 5.1.1 on 2024-09-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0008_alter_historicalmultimediaclassification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimedia',
            name='data',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
