# Generated by Django 5.1.1 on 2024-09-10 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0009_alter_multimedia_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalmultimedia',
            old_name='multimediaClassification',
            new_name='multimediaclassification',
        ),
        migrations.RenameField(
            model_name='multimedia',
            old_name='multimediaClassification',
            new_name='multimediaclassification',
        ),
    ]
