# Generated by Django 5.1.1 on 2024-09-10 23:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0012_rename_multimediaclassification_historicalmultimedia_multimediaclassification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmultimedia',
            name='data',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv', 'flv', 'mkv', 'mpg', 'mpeg', 'webm', '3gp'])]),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='data',
            field=models.FileField(blank=True, null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv', 'flv', 'mkv', 'mpg', 'mpeg', 'webm', '3gp'])]),
        ),
    ]
