# Generated by Django 5.1.1 on 2024-09-30 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0013_alter_historicalmultimedia_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmultimedia',
            name='external_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='historicalmultimedia',
            name='is_local',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='external_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='is_local',
            field=models.BooleanField(default=True),
        ),
    ]
