# Generated by Django 5.0.6 on 2024-07-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='documentclassification',
            name='description',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='documenttypes',
            name='description',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
