# Generated by Django 5.1.1 on 2024-09-10 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_historicaldocument_historicaldocumentclassification_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaldocumentclassification',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical document classification', 'verbose_name_plural': 'historical document classifications'},
        ),
        migrations.AlterModelOptions(
            name='historicaldocumenttypes',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical document types', 'verbose_name_plural': 'historical document typess'},
        ),
        migrations.RenameField(
            model_name='document',
            old_name='documentclassification',
            new_name='documentClassification',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='documenttypes',
            new_name='documentTypes',
        ),
        migrations.RenameField(
            model_name='historicaldocument',
            old_name='documentclassification',
            new_name='documentClassification',
        ),
        migrations.RenameField(
            model_name='historicaldocument',
            old_name='documenttypes',
            new_name='documentTypes',
        ),
    ]
