# Generated by Django 5.1.1 on 2024-09-10 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_rename_documentclassification_document_documentclassification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='documentclassification',
            new_name='documentClassification',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='documenttypes',
            new_name='documentTypes',
        ),
        migrations.RenameField(
            model_name='historicaldocument',
            old_name='documentclassification',
            new_name='documentClassification',
        ),
        migrations.RenameField(
            model_name='historicaldocument',
            old_name='documenttypes',
            new_name='documentTypes',
        ),
    ]
