# Generated by Django 5.1.1 on 2024-09-10 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_rename_documentclassification_document_documentclassification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='documentClassification',
            new_name='documentclassification',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='documentTypes',
            new_name='documenttypes',
        ),
        migrations.RenameField(
            model_name='historicaldocument',
            old_name='documentClassification',
            new_name='documentclassification',
        ),
        migrations.RenameField(
            model_name='historicaldocument',
            old_name='documentTypes',
            new_name='documenttypes',
        ),
    ]
