# Generated by Django 5.1.1 on 2024-09-10 23:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_rename_documentclassification_document_documentclassification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='data',
            field=models.FileField(blank=True, null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'tex'])]),
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='data',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'tex'])]),
        ),
    ]
