# Generated by Django 5.1.1 on 2024-10-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_alter_document_data_alter_historicaldocument_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
