# Generated by Django 4.2 on 2024-01-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True, default="/Isotipo.png", null=True, upload_to=""
            ),
        ),
    ]


# Generated by Django 4.2 on 2024-01-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True, default="/Isotipo.png", null=True, upload_to=""
            ),
        ),
    ]
