# Generated by Django 4.2 on 2024-01-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='/profile_picture/Isotipo.png', null=True, upload_to=''),
        ),
    ]
