# Generated by Django 5.0.6 on 2024-07-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='/profile_picture/Isotipo.png', null=True, upload_to='profile_picture/'),
        ),
    ]
