# Generated by Django 5.1 on 2024-08-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='profile_picture/Isotipo.png', null=True, upload_to='profile_picture/'),
        ),
    ]
